# introduction to numpy

In [1]:
import numpy as np


In [7]:
np. __version__

'2.0.1'

# creating an array using list

In [2]:
arr=np.array([23,4,5,678,90])

In [4]:
arr

array([ 23,   4,   5, 678,  90])

In [5]:
type(arr) 

numpy.ndarray

In [6]:
arr.ndim # to check the dimensions of an array


1

In [4]:
arr.size  # gives the no. of elements present in the array

5

In [6]:
arr.dtype # checks the type of array

dtype('int64')

# slicing and indexing

In [9]:
arr[3:6]

array([678,  90])

In [10]:
arr = np.array([25,10,20,30,40,50,60])
arr

array([25, 10, 20, 30, 40, 50, 60])

In [11]:
arr[4:7]

array([40, 50, 60])

In [13]:
arr[-3:-1]

array([40, 50])

In [7]:
sum(arr) # sum function calculates the sum of the elements in the array

np.int64(800)

In [15]:
np.mean(arr)

np.float64(33.57142857142857)

In [16]:
np.median(arr)

np.float64(30.0)

In [17]:
max(arr)

np.int64(60)

In [18]:
min(arr)

np.int64(10)

# creating array of random numbers

In [20]:
import random

In [29]:
yt=np.random.randint(1,5,10)

In [30]:
yt

array([4, 3, 1, 1, 3, 3, 1, 1, 1, 2], dtype=int32)

In [33]:
count=0
for i in yt:
    if i<3:
        count=count+i
print(count)


7


In [10]:
ls=[[1,2,3],
   [4,5,6],
   [7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
arr2=np.array(ls)

In [12]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr2.ndim  #gives the dimension of the array

2

In [14]:
arr2.shape # gives the no. of rows and columns present in the array

(3, 3)

In [13]:
arr2[0]

array([1, 2, 3])

In [15]:
arr2[2]

array([7, 8, 9])

In [16]:
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr2[1:,1:]

array([[5, 6],
       [8, 9]])

In [20]:
arr2[-1]

array([7, 8, 9])

In [25]:
arr2[1:][1:]

array([[7, 8, 9]])

In [26]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr2[:,0]

array([1, 4, 7])

In [28]:
arr2[1:,1:]

array([[5, 6],
       [8, 9]])

In [29]:
arr2[0:2,1:]

array([[2, 3],
       [5, 6]])

In [30]:
arr2[1:,0:2]

array([[4, 5],
       [7, 8]])

In [34]:
arr2[-2:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [31]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# ones()

In [36]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# zeroes()

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# linspace()

In [8]:
arr3=np.linspace(1,50,10) 

In [9]:
arr3

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [42]:
arr3[3:6]

array([17.33333333, 22.77777778, 28.22222222])

# arange()

In [26]:
np.arange(1,50,10) # here we can see that 5 elements are returned with a space of 10 (step_value)

array([ 1, 11, 21, 31, 41])

# full()

In [28]:
np.full(10,25)

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

# 3d array

In [15]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
ls=arr2

In [17]:
ls=[[[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]],
    [[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]],
    [[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]],
    [[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]]

In [18]:
ls

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [29]:
arr4=np.array(ls)

In [30]:
arr4.ndim

3

In [61]:
arr4.shape

(4, 3, 3)

In [63]:
arr4[1,1:,0:]

array([[4, 5, 6],
       [7, 8, 9]])

In [65]:
arr4[0:2] # to access multiple columns in a 3d array 

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [66]:
arr4[:,0,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [59]:
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [68]:
arr4[0:4:2,1,:]

array([[4, 5, 6],
       [4, 5, 6]])

In [69]:
arr4[-4:,-3,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [74]:
arr4[0:,1:,1:]


array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [76]:
 arr4[:,2,-1::-1]

array([[9, 8, 7],
       [9, 8, 7],
       [9, 8, 7],
       [9, 8, 7]])

In [79]:
arr4[:,2, 0:]

array([[7, 8, 9],
       [7, 8, 9],
       [7, 8, 9],
       [7, 8, 9]])

#  multidimensional array to 1D array

In [62]:
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [31]:
arr4.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
arr4.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# reshape()

In [88]:
arr4.reshape(9,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 1, 2],
       [3, 4, 5, 6],
       [7, 8, 9, 1],
       [2, 3, 4, 5],
       [6, 7, 8, 9]])

In [95]:
full_arr=np.full([2,2],45,dtype=int)

In [96]:
full_arr

array([[45, 45],
       [45, 45]])

# argmin(),argmax() & argsort()

In [98]:
a=np.array([12,13,4,5,5,6], ndmin=1)

In [99]:
a

array([12, 13,  4,  5,  5,  6])

In [100]:
a.argmin() # it returns the index of the smallest value in the array

np.int64(2)

In [101]:
a.argmax() # it returns the index of the  largest value in the array

np.int64(1)

In [130]:
n=a.argsort() # it sorts the elements and returns the sorted index of the element 

In [129]:
a

array([12, 13,  4,  5,  5,  6])

In [131]:
n

array([2, 3, 4, 5, 0, 1])

In [71]:
arr5=[[[2,3,4],
      [6,3,6],
      [8,7,0]],
      
      [[2,3,4],
      [6,3,6],
      [8,7,0]],
      
      [[2,3,4],
      [6,3,6],
      [8,7,0]],
      
      [[2,3,4],
      [6,3,6],
      [8,7,0]]]

In [72]:
np.array(arr5)

array([[[2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]]])

# vstack() and concatenate()

In [80]:
np.vstack((arr4,arr5))

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]]])

In [81]:
np.concatenate((arr4 , arr5), axis=0 )

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]]])

# hstack() 
#joining the arrays horizontally

In [82]:
np.hstack((arr4,arr5))

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]]])

In [83]:
np.concatenate((arr4 , arr5), axis=1 )

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [2, 3, 4],
        [6, 3, 6],
        [8, 7, 0]]])